# Generated by Django 5.2 on 2025-05-11 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduce el nombre completo del producto.', max_length=45)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduce el nombre completo del producto.', max_length=100)),
                ('mail', models.EmailField(help_text='Introduce el nombre completo del producto.', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Introduce el nombre completo del producto.', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Introduce el nombre completo del producto.', max_length=100, null=True)),
                ('profile_pic', models.ImageField(upload_to='users/', max_length=255, null=True, blank=True)),
                ('profile_desc', models.TextField(blank=True, help_text='Introduce el nombre completo del producto.', max_length=500, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(help_text='Introduce el precio del producto.')),
                ('name', models.CharField(blank=True, help_text='Introduce el nombre del producto.', max_length=45, null=True)),
                ('description', models.CharField(blank=True, help_text='Introduce la descripción del producto.', max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('disponibility', models.CharField(blank=True, choices=[('en_venta', 'En venta'), ('comprado', 'Comprado'), ('reservado', 'Reservado'), ('cancelado', 'Cancelado')], default='en_venta', help_text='Introduce la disponibilidad del producto.', max_length=20, null=True)),
                ('state', models.CharField(blank=True, choices=[('como_nuevo', 'Como nuevo'), ('muy_bueno', 'Muy bueno'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('no_funciona', 'No funciona')], default='bueno', help_text='Introduce el estado del producto.', max_length=30, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Introduce la categoría del producto.', on_delete=django.db.models.deletion.RESTRICT, to='core.category')),
                ('user', models.ForeignKey(help_text='Introduce el nombre del producto.', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(blank=True, help_text='Introduce el nombre completo del producto.', null=True, verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Introduce el nombre completo del producto.', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user', models.ForeignKey(help_text='Introduce el nombre completo del producto.', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.CharField(blank=True, help_text='Introduce el precio ofrecido para el producto.', max_length=45, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.user')),
            ],
        ),
    ]
