# Generated by Django 5.2 on 2025-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='disponibility',
            field=models.CharField(blank=True, choices=[('en_venta', 'En venta'), ('vendido', 'Vendido'), ('reservado', 'Reservado'), ('cancelado', 'Cancelado')], default='en_venta', help_text='Introduce la disponibilidad del producto.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(help_text='Correo electrónico del usuario', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Nombre del usuario.', max_length=100),
        ),
    ]
