# Generated by Django 5.2 on 2025-05-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(blank=True, choices=[('Como nuevo', 'como_nuevo'), ('Muy bueno', 'muy_bueno'), ('Bueno', 'bueno'), ('Regular', 'regular'), ('No funciona', 'no_funciona')], default='Bueno', help_text='Introduce el estado del producto.', max_length=30, null=True),
        ),
    ]
