# Generated by Django 5.2 on 2025-05-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Introduce la descripción del producto.', max_length=5000, null=True),
        ),
    ]
