# Generated by Django 5.2 on 2025-06-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_picture_product_picture1_product_picture2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(blank=True, choices=[('Como nuevo', 'como_nuevo'), ('Muy bueno', 'muy_bueno'), ('Bueno', 'bueno'), ('Regular', 'regular'), ('Lo ha dado todo', 'Lo_ha_dado_todo')], default='Bueno', help_text='Introduce el estado del producto.', max_length=30, null=True),
        ),
    ]
