# Generated by Django 5.2 on 2025-06-08 13:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nombre de la categoría del producto.', max_length=45),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offered_price',
            field=models.CharField(blank=True, help_text='Precio ofrecido por el usuario.', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(help_text='Producto al que se hace la oferta.', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.product'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(help_text='Usuario que realiza la oferta.', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(help_text='Producto que ha sido comprado.', on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='Usuario que ha realizado la compra.', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Categoría a la que pertenece el producto.', on_delete=django.db.models.deletion.RESTRICT, to='core.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada del producto.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='disponibility',
            field=models.CharField(blank=True, choices=[('en_venta', 'En venta'), ('vendido', 'Vendido'), ('reservado', 'Reservado'), ('cancelado', 'Cancelado')], default='en_venta', help_text='Estado de disponibilidad del producto (en venta, vendido, etc.).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Título o nombre del producto.', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture1',
            field=models.ImageField(blank=True, help_text='Imagen principal del producto.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture2',
            field=models.ImageField(blank=True, help_text='Imagen adicional del producto.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture3',
            field=models.ImageField(blank=True, help_text='Imagen adicional del producto.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture4',
            field=models.ImageField(blank=True, help_text='Imagen adicional del producto.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture5',
            field=models.ImageField(blank=True, help_text='Imagen adicional del producto.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio del producto en euros (con decimales).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(blank=True, choices=[('Como nuevo', 'como_nuevo'), ('Muy bueno', 'muy_bueno'), ('Bueno', 'bueno'), ('Regular', 'regular'), ('Lo ha dado todo', 'lo_ha_dado_todo')], default='Bueno', help_text='Condición del producto (como nuevo, bueno, etc.).', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(help_text='Usuario que ha publicado el producto.', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_value',
            field=models.IntegerField(blank=True, help_text='Valor numérico de la valoración (0 a 5).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(help_text='Usuario que ha recibido la valoración.', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, help_text='Código enviado por correo para verificar la cuenta.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_expiry',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de expiración del código de verificación.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Ubicación del usuario.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(help_text='Correo electrónico usado para iniciar sesión.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Nombre completo del usuario.', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Contraseña del usuario (se almacena encriptada).', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_desc',
            field=models.TextField(blank=True, help_text='Descripción pública del perfil del usuario.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario.', null=True, upload_to='users/'),
        ),
    ]
